### ISSUE TITLE
Test recovered models against Model Compiler 2.1.1-Bravo

### ISSUE THREAD

**Issue by mpostol** [mpostol/UA-Nodeset#97]
## Describe the problem

All recovered models must be tested against compliance with the [Model Compiler](https://github.com/mpostol/UA-ModelCompiler#model-compiler). 

Check out the current version of the [Model Compiler 2.1.1-Bravo](https://github.com/mpostol/UA-ModelCompiler/releases/tag/2.1.1-Bravo).

## Describe the solution you'd like

To test you must prepare scripts calling the `Model Compiler` and executed them for all recovered models.
The preliminary script template shall be as follows

```TXT
set COMPILER=OOI.ModelCompilerUI
"%1\%COMPILER%" -d2 "<ModelName>.xml" -cg "<ModelName>[.csv]" -o "<ModelName>" -console
```

Test the template using the selected model and review it if needed. All problems must be reported.

Partially it contributes to mertyusaatag/UA-Nodeset#14.
Partially it contributes to mpostol/OPC-UA-OOI#653.

- [x] IEC61850

**Comment by mpostol** [comment]
For 

```txt
-d2 "Opc.Ua.IEC61850-7-3.Model.xml" -cg "IEC61850-7-3.csv" -o "IEC61850-7-3" -console
```
we are getting an error related to XML, but ``Opc.Ua.IEC61850-7-3.Model.xml` was generated using the XML Serializer from .NET.
 
```txt
The string '20/11/2020' is not a valid AllXsd value.
at System.Xml.Schema.XsdDateTime..ctor(String text, XsdDateTimeFlags kinds) 
at System.Xml.XmlConvert.ToDateTime(String s, XmlDateTimeSerializationMode dateTimeOption) 
at OOI.ModelCompiler.ModelCompilerValidator.Validate2(IList`1 designFilePaths, String identifierFilePath, Boolean generateIds) in C:\VS.git\github.mpostol\UA-ModelCompiler\Opc.Ua.ModelCompiler\ModelDesignerValidator.cs:line 1135 
at OOI.ModelCompiler.ModelGenerator2.ValidateAndUpdateIds(IModelGeneratorValidate model) in C:\VS.git\github.mpostol\UA-ModelCompiler\Opc.Ua.ModelCompiler\ModelGenerator2.cs:line 108 
at OOI.ModelCompilerUI.ModelCompilerAPI.Execute(IModelGeneratorGenerate generateParameters, IModelGeneratorValidate validateParameters) in C:\VS.git\github.mpostol\UA-ModelCompiler\ModelCompilerUI\ModelCompilerAPI.cs:line 24 
at OOI.ModelCompilerUI.ModelCompilerAPIInternal.Execute(IModelGeneratorGenerate generateParameters, IModelGeneratorValidate validateParameters) in C:\VS.git\github.mpostol\UA-ModelCompiler\ModelCompilerUI\ModelCompilerAPIInternal.cs:line 211 
at OOI.ModelCompilerUI.EntryPoint.ProcessCommandLine(String commandLine, Boolean noGui, IGUIHandling guiHandling) in C:\VS.git\github.mpostol\UA-ModelCompiler\ModelCompilerUI\EntryPoint.cs:line 98
``

**Comment by mpostol** [comment]
Incompatible `PublicationDate`  format detected:

- OPC-UA-OOI\SemanticData\UAModelDesignExport\XML\UA Model Design.xsd
- UA-ModelCompiler\Opc.Ua.ModelCompiler\UA Model Design.xsd

``` txt
        <xs:attribute name="PublicationDate" type="xs:string" use="optional" />
```

- OPC-UA-OOI\SemanticData\UANodeSetValidation\XML\UANodeSet.xsd

``` txt
    <xs:attribute name="PublicationDate" type="xs:dateTime" />
```

- UA-ModelCompiler\Opc.Ua.ModelCompiler\ModelDesignerValidator.cs

``` txt
modelInfo.PublicationDate = XmlConvert.ToDateTime(ns.PublicationDate, XmlDateTimeSerializationMode.Utc)
```

- IEC61850\ModelDesign\Opc.Ua.IEC61850-7-3.Model.xml

``` txt
PublicationDate="20/11/2020"
```

**Comment by mpostol** [comment]
- Must be fixed in asp - add validation and workaround to fix in case the date is not valid
- Workaround `20/11/2020` => `2020-11-20T00:00:00Z`

**Comment by mpostol** [comment]
Compiler error:

The node has a parameter without a name: MultiplierKind.

```txt
at OOI.ModelCompiler.ModelCompilerValidator.ImportParameters(NodeDesign node, Parameter[]& parameters, String parameterType) in C:\VS.git\github.mpostol\UA-ModelCompiler\Opc.Ua.ModelCompiler\ModelDesignerValidator.cs:line 3077 
at OOI.ModelCompiler.ModelCompilerValidator.ImportType(TypeDesign type) in C:\VS.git\github.mpostol\UA-ModelCompiler\Opc.Ua.ModelCompiler\ModelDesignerValidator.cs:line 2711 
at OOI.ModelCompiler.ModelCompilerValidator.Import(NodeDesign node, NodeDesign parent) in C:\VS.git\github.mpostol\UA-ModelCompiler\Opc.Ua.ModelCompiler\ModelDesignerValidator.cs:line 2316 
at OOI.ModelCompiler.ModelCompilerValidator.Validate2(IList`1 designFilePaths, String identifierFilePath, Boolean generateIds) in C:\VS.git\github.mpostol\UA-ModelCompiler\Opc.Ua.ModelCompiler\ModelDesignerValidator.cs:line 1173 
at OOI.ModelCompiler.ModelGenerator2.ValidateAndUpdateIds(IModelGeneratorValidate model) in C:\VS.git\github.mpostol\UA-ModelCompiler\Opc.Ua.ModelCompiler\ModelGenerator2.cs:line 108 
at OOI.ModelCompilerUI.ModelCompilerAPI.Execute(IModelGeneratorGenerate generateParameters, IModelGeneratorValidate validateParameters) in C:\VS.git\github.mpostol\UA-ModelCompiler\ModelCompilerUI\ModelCompilerAPI.cs:line 24 
at OOI.ModelCompilerUI.ModelCompilerAPIInternal.Execute(IModelGeneratorGenerate generateParameters, IModelGeneratorValidate validateParameters) in C:\VS.git\github.mpostol\UA-ModelCompiler\ModelCompilerUI\ModelCompilerAPIInternal.cs:line 211 
at OOI.ModelCompilerUI.EntryPoint.ProcessCommandLine(String commandLine, Boolean noGui, IGUIHandling guiHandling) in C:\VS.git\github.mpostol\UA-ModelCompiler\ModelCompilerUI\EntryPoint.cs:line 98
```

**Comment by mpostol** [comment]
The model is to be tested using the new version of the ModelDesign Compiler (mdc.exe) Version: 3.0.0.41853
